### ISSUE TITLE
Hover tooltip

### ISSUE THREAD

**Issue by MarkMcDaniels** [codeforgreenville/hackgreenville-com#10]
@allella Per @pamelawoodbrowne 's notice, the only way to read the description on a calendar event was to click on it. I wrote a small script that fixes that, but I don't have access to send you a pull request. Can I have access please?

**Comment by allella** [comment]
@MarkMcDaniels you should be good now. Thanks

**Comment by allella** [comment]
@MarkMcDaniels I changed the JS include so it's relative to the public directory where the /js/hover-text.js lives.

The /js/hover-text.js is now including in the page, but on the live site when I switch to the Hover branch it doesn't do anything after browser refreshing.

As mentioned in #3, we'll likely prefer to move all the JS and CSS includes into laravel-mix, but we can at least try to get this thing working and then worry about doing things the "Laravel way".

**Comment by allella** [comment]
Forgot to reference the commit
https://github.com/codeforgreenville/hackgreenville-com/commit/8aafa5ea2ebaf19cd17875e9067450216728d886

**Comment by allella** [comment]
@zach2825 it seems like you had an improvement on this request in the most recent PR and work.  I've assigned this to you since it may already be done, or close to done.

**Comment by zach2825** [comment]
Hi @allella. 
I don't think I did anything for the hover text. But, I'd like to. What is this referencing and can we use something like bootstrap popover so we don't have to include another lib? 

https://getbootstrap.com/docs/4.0/components/popovers/

**Comment by allella** [comment]
@zach2825 Sorry, I was thinking this was a thing for the Add to Calendar.  Did you load a new calendar tool? If so, I think this issue was that the current calendar doesn't show any more details and if you click it then it does the Add to Calendar for Google Calendar.

@MarkMcDaniels did you have a PR to submit on this?

**Comment by zach2825** [comment]
Yeah I did add swal as a pop up what confirmation before adding the calendar event to your personal calendar and in that pop up it shows the event details

**Comment by MarkMcDaniels** [comment]
I did. I haven't built an environment to test it yet, because I added it at
the bottom of a page instead of enqueuing it. Tonight I should have my
laravel local env setup so I can actually do some work that I can see
results. The script I wrote should work though.

**Comment by MarkMcDaniels** [comment]
Zach, can you explain what you've done to the calendar so that I don't replicate work?

**Comment by zach2825** [comment]
Yes, when I upgraded laravel the original calendar plugin was not compatible. For the new calendar I implemnted Fullcalender. For the calendar events I used swal to show the calendar title and body and add a button to add it to the users calendar and a button to close the alert. I can share a few screenshots with you in the morning.

**Comment by zach2825** [comment]
![Selection_20191103220035](https://user-images.githubusercontent.com/4049321/68264185-02887800-0016-11ea-86bd-ed9bb8dd034d.png)

I just realized I had a screenshot already.

**Comment by zach2825** [comment]
you should be able to see the changes here
https://github.com/codeforgreenville/hackgreenville-com/pull/15

**Comment by allella** [comment]
@zach2825 I know I've confused this issue by mentioning the Add to Calendar. I think the initial issue involves people wanting to see some of the event info since the calendar truncates the titles.

For instance, in the screenshot it says "Back to Basics And"  but I couldn't tell you which group or what the topic is.

So, this was probably asking for a mouseover tip that showed more details.  Since hovering isn't so good in mobile I think we'd prefer a pop-up like you have.  So, the question is if we can have the pop-up shown the basic event info, a want to see more info, and the Add to Calendar feature.

**Comment by zach2825** [comment]
That's what it does right now.the button text is confusing it probably should say "add to my calendar" or something

**Comment by allella** [comment]
Cool. If it's easy to put a the date, time, link to the meetup URL and homepage in there then I think that would give about everything someone might want.  Also, does the pop-up offer a (X) for the corner to close? If we had an (X) I suppose the cancel button isn't needed.

**Comment by zach2825** [comment]
Yes, we can make the body of the sweetalert have any html we want. 

What do you think about updating the api endpoint to send back the correct url to the event? Right now it just sends back the meetup.com events url..
![image](https://user-images.githubusercontent.com/4049321/68311920-4748f900-0080-11ea-9d0b-c27a40c38e68.png)

**Comment by allella** [comment]
@zach2825 the Meetup.com events should now have a valid event link under the "url" field in the events API https://events.openupstate.org/api/gtc?tags=1

The meetup API changed from v2 to v3 so that field was no longer populating.

**Comment by zach2825** [comment]
thank you I'll post a PR soon that uses that

**Comment by zach2825** [comment]
I think this issue has been resolved. It can be reopened if not. I'll leave it open for a few days in case there's more to talk about on it.
