### ISSUE TITLE
Dockerize the Laravel / PHP / Dev Stack

### ISSUE THREAD

**Issue by allella** [codeforgreenville/hackgreenville-com#105]
@MarkMcDaniels brought up the challenges of jumping into the Code For Greenville projects due to the dev setup tasks and effort.

During the last [CFG meeting](https://codeforgreenville.org/) @jeremywight @allella and @cscully thought we should Dockerize some of the projects. 

This HG repo may be a good first candidate.

We talked a bit about it already on the [Slack](https://app.slack.com/client/TDPR0G67P/CDP1BRXKK?cdn_fallback=1), but I figured to leave this open for some planning and in case others are interested.

**Comment by allella** [comment]
![image](https://user-images.githubusercontent.com/1777776/114499835-e8809b00-9bf4-11eb-9023-3f5d51c49d8a.png)

**Comment by zach2825** [comment]
I don't think this should be too hard to do. Laravel added "sail".

https://laravel.com/docs/8.x/sail

**Comment by allella** [comment]
@csculley is taking a first crack at this right now.

**Comment by csculley** [comment]
I've added Laravel Sail to the project on the `csculley/dockerize` branch, but I've been having issues fully bringing up the site, running into permission issues with `/var/www/html`.
Feel free to try to bring up the project on `csculley/dockerize` with me to make sure that it's working, by either doing `vendor/bin/sail up` or `vendor/bin/sail up -d`!

**Comment by allella** [comment]
I ran it and it definitely got pretty far before hanging on this line

> laravel.test_1  | [Wed May  5 01:38:54 2021] 172.20.0.1:34274 Closing

Maybe I just need to wait 20 more minutes.

I thought Docker was magic. The more I see it in action the more it looks like a glorified shell script compiling things from source.

I think we'll also want to update the docs with notes on installing required PHP extensions, like sqlite3 and dom. It seem trivial and it's  mentioned in [Forking the Project and Getting it Running > Step 3](https://github.com/codeforgreenville/hackgreenville-com/blob/develop/CONTRIBUTING.md#forking-the-project-and-getting-it-running) under the requirements, but it's glossed over given how much they will break things if they aren't already installed locally, for both local install and an attempt at Docker.

Composer won't run without those extensions so that initially blocked the _composer install_ needed to install Sail.

IDK, it sort of defeats the purpose to need to install most of PHP just to try and install a virtual environment that runs a PHP app, but what do I know.

Prerequisite (on Ubuntu)
`sudo apt install php-sqlite3 php-dom
`

```
composer install
vendor/bin/sail up
```

I'll try to run it again if it doesn't get past the current positiion.

Thanks @csculley

**Comment by zach2825** [comment]
Lame, I can't test this. I'm running PHP8 and the things are the current versions are not compatible.

**Comment by allella** [comment]
@csculley is making progress on Docker.  We've been talking through some pros and cons and questioning if it's going to help to run Docker vs local development besides for Windows users.

[Another idea for setting up a dev environment is something like GitPod](https://github.com/freeCodeCamp/chapter/blob/master/CONTRIBUTING.md#using-gitpod), which requires an account, but allows for clicking a button / link on a pull request and getting a functional dev environment in the cloud.  It has a 50 hour / month free tier, which I suspect could be more than enough for the folks who have time or system limitations that make local development impractical.

@MarkMcDaniels what do you think? Was your issue trying to develop on Windows and would something like GitPod be even more desirable than having to run WSL + Docker to get a working dev environment setup?

**Comment by allella** [comment]
Based on what csculley found, it may be as much work for folks to get WSL and Docker installed locally as it would to follow the packages and daemons to run a local tech stack.

Docker definitely solves some problems, but Chris thought it would be useful for production than development.

In my limited experience with supporting Docker for new contributors on [Chapter](https://github.com/freeCodeCamp/chapter), especially for those using Windows, it's possible to spend as much time troubleshooting WSL and Docker as troubleshooting a local Laravel and database environment.

GitPod, or similar, are intended to be a more one-click and ephemeral dev environment. Here's an example of a [GitPod config for the related Chapter project](https://github.com/freeCodeCamp/chapter/blob/master/.gitpod.yml) and I could ask the folks I know in Chapter for pointers if someone wants to go down this path. 

I just tested GitPod on a random Chapter pull request and it took about a minute for it to load everything up and have a rendered app / website and a functional code environment. You don't even have to register for an account because you can login with GitHub authorization.

For those who want to dabble before figuring out a more local / custom development environment, GitPod seems to target the issue Mark initially described and it currently allows for up to 50/hours per month for free.

@MarkMcDaniels do you think this would be a better solution?  It would create upfront work to configure GitPod, but if you want to see it in action, then let me know and I can find a stable looking PR on Chapter as an example to see how it works.
