### ISSUE TITLE
Join slack typeform integration is broken

### ISSUE THREAD

**Issue by risdenk** [codeforgreenville/hackgreenville-com#114]
It looks like the referenced typeform url is no longer valid: https://hackgreenville.typeform.com/to/sBMjCF

https://github.com/codeforgreenville/hackgreenville-com/blob/master/resources/views/slack/sign-up.blade.php#L9

<img width="1700" alt="Screen Shot 2022-05-28 at 14 45 19" src="https://user-images.githubusercontent.com/3384157/170838876-10392aec-c38b-49fb-b3ef-e688504f1a3b.png">

**Comment by allella** [comment]
@Soulfire86 I believe this was the TypeForm you manage for HackGreenville Slack join requests. It's showing that the form is "closed" as mentioned above.

**Comment by allella** [comment]
@risdenk are you still looking for an invite to the HG Slack? If so, we can manually add you while we're working on #112 or other solutions.

**Comment by allella** [comment]
@risdenk [the form](https://hackgreenville.com/join-slack) is working again (still has a monthly limit) so you can submit to it, or DM me on Twitter (@allella) with an email address.  Thanks
