### ISSUE TITLE
Update composer.json versions for PHP and PHP Extensions

### ISSUE THREAD

**Issue by allella** [codeforgreenville/hackgreenville-com#124]
Per the conversation at https://github.com/codeforgreenville/hackgreenville-com/pull/121#issue-1354432062 we may want to update Composer to PHP 7.3 +, since we're now on [Laravel 8 and since it requires PHP 7.3](https://laravel.com/docs/8.x/upgrade#php-7.3.0-required).

Also, Bogdan suggested we could make the _required-dev_ directives for the SQLite extensions use wildcard versions.

```
  "ext-pdo_sqlite": "*",
  "ext-sqlite3": "*",
```

**Comment by bogdankharchenko** [comment]
We should use PHP8.1, since its on the server.

We can then bump the project to laravel 9

**Comment by allella** [comment]
That's fine with me if @zach2825 agrees we're ready and should make the move to Laravel 9.

**Comment by allella** [comment]
Closing as #126 should have closed this.

Larvel 9 would be another issue if / when we're ready to go that route.
