### ISSUE TITLE
Move API URLs out of the Code and Into Config / Env

### ISSUE THREAD

**Issue by allella** [codeforgreenville/hackgreenville-com#13]
@zach2825 This isn't critical, but this is the one commit that was in master and not develop.

https://github.com/codeforgreenville/hackgreenville-com/commit/05dc3d2e641e4c07904142669f81fd77e1dfac17

So, if you want to apply the changes, or something better than this, then feel free to do a PR.

I haven't setup a dev environment for myself yet, or I would have submitted it as a PR myself.

One question is if we should move the entire URL into the config / .env, or if just the domains are worth moving.

The URL paths are very specific to the APIs, whereas the domain names for the APIs have already changed a couple/few times due to moving servers.

https://github.com/codeforgreenville/hackgreenville-com/commit/05dc3d2e641e4c07904142669f81fd77e1dfac17

**Comment by zach2825** [comment]
This PR contains the work that you did from the master branch, this PR just makes sure the work is persisted in the dev branch. 
https://github.com/codeforgreenville/hackgreenville-com/pull/14

**Comment by allella** [comment]
Merged #14. Closing.
