### ISSUE TITLE
Color of Logo Slightly Off From Background

### ISSUE THREAD

**Issue by allella** [codeforgreenville/hackgreenville-com#20]
Via @ajhodges 

> "the background color of the logo is slightly different than the color of the header "

via [the HG conversation](https://app.slack.com/client/T0420TN6E/C0420TN6U/thread/C0420TN6U-1575574236.073000?cdn_fallback=1).

**Comment by ajhodges** [comment]
Logo is showing #251d4a and header is showing #201748. Any chance at a logo with a transparent background?

**Comment by zach2825** [comment]
I removed the background color of the logo. Thank you for the suggestion.
