### ISSUE TITLE
Add Analytics Tracking

### ISSUE THREAD

**Issue by allella** [codeforgreenville/hackgreenville-com#23]
If we're okay with Google Analytics then I can create the tracking account under the CFG Google Apps so it's owned and linked to it, instead of someone's personal account.

**Comment by zach2825** [comment]
I'd be game for this! do it, maybe we should create a dokuwiki or something where we can document credentials and notes and things like this

**Comment by allella** [comment]
Well, I know Google Analytics allows for setting permissions with various levels of access, so I figure we can associate the main account with the CFG and then give permissions by request for Analytics.

The point about having a shared place for CFG credentials is well taken.  To some degree this is less of a concern about Code For America hosts and manages the Google Apps account for codeforgreenville.com email addresses. We've started registering accounts with those emails so if someone were to fall off the planet then CFA could likely help regain access to the email accounts used to setup access.

**Comment by allella** [comment]
```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-154722329-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-154722329-1');
</script>

```

**Comment by allella** [comment]
@zach2825 if you want access to the Analytics then shoot me your Google email in a PM.
