### ISSUE TITLE
"Events Site" links on the Orgs Page all go to the Same Internal URL

### ISSUE THREAD

**Issue by allella** [codeforgreenville/hackgreenville-com#32]
On https://stage.hackgreenville.com/orgs the "Events Site" links to the right of each organization loop back to the current page.

Also, I suspect we could rename that anchor text to "Register" or "Events".

**Comment by allella** [comment]
@zach2825 I think there is this and perhaps a couple other buggy or usability things which may be worth handling before going live with a release.

Would you say we're in a position to ask the HG community to review the stage site and post issues on anything they find?

**Comment by zach2825** [comment]
@allella I'd say the site is an in a release ready state. We could add more content on the homepage in the sponsors and join us sections. like what those sections are and what they mean to us. But that content can be added later..

**Comment by allella** [comment]
Thanks @zach2825  I'll reach out for some testers. Though, I think this is a legit bug.  All of the links go nowhere useful.   They should go to the event homepage URL in the API.

Thank again.
