### ISSUE TITLE
Homepage Event Cards are HTML Entity Encoding the Card Content

### ISSUE THREAD

**Issue by allella** [codeforgreenville/hackgreenville-com#35]
The `<br/>` tag is an example of the encoding.  It's good we're sanitizing the content to avoid XSS, but it's leaving unintended HTML tag artifacts.

![image](https://user-images.githubusercontent.com/1777776/71939397-7e22b480-3180-11ea-858f-e3d3707eb8ca.png)

**Comment by allella** [comment]
@zach2825 What if, instead of fixing the encoding issue, we just don't show the description? It's truncated already and we could fix a bunch more events in the space without it being very long.

@jeremywight 's overflow:scroll was trying to keep there from being so much whitespace and removing the descriptions would help with that too.

**Comment by zach2825** [comment]
I understand why the scroll was added. But, that areas only meant to show a few events that are coming up. It's not meant to list as much as possible. If people want to see all the events we have the events page. 
For the homepage, and I should have created issues or a roadmap here in github instead of trello, but on the homepage I want to add action items or details for sponsors and for new people that are showing interest in the community. That stuff would fill out the white areas better.

**Comment by allella** [comment]
Sounds good. I've been treating this release like more of a feature freeze at this point so if we can work with what we have and trim it down then it should suffice to get us out of the gate.

I do feel the event descriptions aren't necessary and could help with the whitespace issue now and later.  You agree?

Also, not part of this issue, but clicking those cards are very actionable. Were you intending to add a link to the HG events page or the org's homepage or events page?

**Comment by allella** [comment]
RE: clicking the cards, I meant to say the pop-up isn't very actionable.  I found myself wanting to have an option to see more info.

**Comment by zach2825** [comment]
I agree I just added them so at a glance people could tell the difference between 2 cards just in case they both had the same title. But, I don't think that is a thing.

**Comment by allella** [comment]
Yeah, I think we have enough events we're unlikely to get two back-to-back, even a slow December month.

**Comment by zach2825** [comment]
Removed the short description. Is not an issue anymore.

**Comment by allella** [comment]
Looking good.
