### ISSUE TITLE
homepage events list make them aligned 

### ISSUE THREAD

**Issue by zach2825** [codeforgreenville/hackgreenville-com#38]
![Selection_20200108115959](https://user-images.githubusercontent.com/4049321/72004365-3dc34500-3219-11ea-8cee-037bf544fc44.png)

**Comment by zach2825** [comment]
I mocked that up to show the idea.

**Comment by allella** [comment]
That works. Anything to cut down on the whitespace and scrolling would be great until we get more content.

**Comment by allella** [comment]
I'd still vote for removing the description to show more events over fewer + descriptions, but do whatever you like.

Thanks,
Jim
