### ISSUE TITLE
Calendar is showing incorrect time (not local in GVL).

### ISSUE THREAD

**Issue by Mozillex** [codeforgreenville/hackgreenville-com#4]
Calendar is showing incorrect time (not local in GVL). Perhaps server time not == to GVL time??

**Comment by allella** [comment]
Server time looked good on EDT so could be a Laravel package or config.  @magoun @kevindees was invited to the repo but not sure if he's going to get the issue notice if it's something introduced in the calendar package.

**Comment by Mozillex** [comment]
For clarification: the times in error were for the events.
i.e. - the 3 Calendar events for tonight (7/24/18) showed 10p and 11p, as opposed to 6p and 7p:
![screen shot 2018-07-24 at 9 18 11 pm](https://user-images.githubusercontent.com/25697042/43174300-4f951faa-8f87-11e8-9c7e-f86fc845c60b.png)

**Comment by allella** [comment]
I've pulled down the calendar navigation link on the site in the meantime since we have "Events" doing much the same, but the page will still render by direct visit.
https://hackgreenville.com/calendar

**Comment by allella** [comment]
I checked the package to see if there was any timezone issues reported but nothing showed up
https://github.com/maddhatter/laravel-fullcalendar/issues?utf8=%E2%9C%93&q=timezone

**Comment by allella** [comment]
@magoun I see the events pulled from Ed's API in app/Http/Helpers/helpers.php are in UTC format and then a printTime method in the helpers.php doing a timezone conversion.

Anybody have a good idea on the best place to do the same conversion for the calendar?  Seems like we should have one method that does this for the $events data arrays coming from the APIs instead of modifying it at the presentation layer for every event.

```
/**
 * Convert event timestamp into readable format for display
 * Use Carbon package for less DateTime headaches...
 */
use Carbon\Carbon;
function printTime ($date) {
  $displayTime = Carbon::createFromFormat('Y-m-d\TH:i:s\Z',
                                            $date,
                                            'UTC');

  return $displayTime->tz(config('app.timezone'))->format('g:i A, D j M y');
}
```

**Comment by magoun** [comment]
I should probably pipe all the events through the time zone conversion immediately after making the API call, as part of post processing. That way, any functions that use the data won't need to account for timezone.

**Comment by allella** [comment]
This has been fixed.  Seems like the data manipulation in a helper.php should really be in a model but at least things work and are a bit cleaner.

There is now a $event->localtime which is a Carbon date that the views and then format as needed. This prevents views from having to do date math timezone conversions, which is out of the scope of what a view should do.
