### ISSUE TITLE
add cache busting

### ISSUE THREAD

**Issue by zach2825** [codeforgreenville/hackgreenville-com#43]
https://laravel.com/docs/6.x/mix#versioning-and-cache-busting

When we deploy style updates we want everyone to see those changes right away and laravel gives you a clean way to do that out of the box.

**Comment by allella** [comment]
Closing.

@zach2825 have you tried doing "Closes #43" syntax in the PRs? I think putting that into the PR comment might make it auto-close the issue when the PR is merged.

**Comment by zach2825** [comment]
I usually work in jira I forgot about that ability. I'll start adding it. Thank you
