### ISSUE TITLE
For this repository in the repo settings make the default merge branch "develop"

### ISSUE THREAD

**Issue by zach2825** [codeforgreenville/hackgreenville-com#45]
Right now when you submit a new PR it defaults to "magoun/sccodes-php-track-project/compare/master" which was the original repo I think. But, it would be nice to have it default to this repository going forward.

**Comment by allella** [comment]
Ah, yes, @jeremywight might have run into this issue.  I'm on board, but where is this set? On Github?

**Comment by allella** [comment]
Alright, I've changed the default branch to develop, but does that fix the "magoun/sccodes-php-track-project/compare/master" connection?

**Comment by zach2825** [comment]
When I click the new PR button
![Selection_20200112094016](https://user-images.githubusercontent.com/4049321/72220543-a82cfb80-351f-11ea-8822-e753ca29fcd6.png)

It tries to merge to the wrong repository
![Selection_20200112094041](https://user-images.githubusercontent.com/4049321/72220553-b549ea80-351f-11ea-858b-788b476a4900.png)

I think there is where you would change that setting. 
![Selection_20200112094206](https://user-images.githubusercontent.com/4049321/72220569-e1fe0200-351f-11ea-8fa8-935c4138833f.png)

**Comment by allella** [comment]
@zach2825  [I changed the setting to develop yesterday](https://github.com/codeforgreenville/hackgreenville-com/issues/45#issuecomment-573331199). Please let me know if that fixed it.
