### ISSUE TITLE
Calendar page is showing duplicate events for some days

### ISSUE THREAD

**Issue by zach2825** [codeforgreenville/hackgreenville-com#53]
https://stage.hackgreenville.com/calendar

![image](https://user-images.githubusercontent.com/4049321/73008975-9e3bb000-3ddd-11ea-9908-e98ab1a422ca.png)

**Comment by allella** [comment]
@zach2825 do we think it's an issue with the events API?

**Comment by zach2825** [comment]
I'm not sure. I won't be able to check until after 5 or 6. todays meeting heavy lol
