### ISSUE TITLE
Improve on color schema

### ISSUE THREAD

**Issue by zach2825** [codeforgreenville/hackgreenville-com#54]
Maybe we could use something like this site to generate the sites colors that might contrast a little better. https://coolors.co/

I generated the color schema from a greenville city page but in practice it looks dated or  to dark or something. I don't know what it needs but IMO it needs something.

Maybe these colors? 
https://coolors.co/201748-48beff-3dfaff-43c59e-3d7068

**Comment by zach2825** [comment]
So the nav might looks something like this. 
![image](https://user-images.githubusercontent.com/4049321/73009488-acd69700-3dde-11ea-8f20-fbede009ff21.png)

**Comment by allella** [comment]
Doesn't seem we've had takers on the need for the background change.

The color palette is at https://hackgreenville.com/styles so posting that in case we circle back to this later.
