### ISSUE TITLE
Upcoming Events on the Homepage are Often Lacking Detail

### ISSUE THREAD

**Issue by allella** [codeforgreenville/hackgreenville-com#58]
The screenshot here shows an example of the issue.

It's unclear which group is hosting the meetups and there's no way to see more details that clarify the issue.

Perhaps we can list the organization's name instead of the event name.  Then, in the pop-up we have the event title, a link to the event homepage, or some such?  

As far as I'm concerned, it's fine if people leave the website, so we don't need to worry making it easy for people to click away to the actual event.

![image](https://user-images.githubusercontent.com/1777776/74690226-3f830f80-51ac-11ea-8725-b9c92b2bc3cf.png)

**Comment by JSn1nj4** [comment]
Would it be alright if I helped out with this one?

**Comment by allella** [comment]
Sure. @Nunie123 should be able to lend a hand if there are questions.

We've been doing Pull Requests against the develop branch, rather than master.

The README should be pretty well up to date, but if you have any issues or improvements, then please let us know.

Thanks

**Comment by allella** [comment]
Sorry, I meant @zach2825 could help. Sorry Ed.

**Comment by allella** [comment]
@JSn1nj4  I noticed the cancelled events still show on the homepage with no indication the event was cancalled.

I believe @zach2825  did work on #66  to deal with #63 on the events and calendar.

Do you have time to do another PR to either hide or somehow make it apparent that events on the homepage are cancelled?

**Comment by allella** [comment]
@JSn1nj4  The Code For Greenville events are not cancelled in the API. Though, some of them should be cancelled, so we could use them as a test.

I think https://stage.hackgreenville.com/events is still using older info because the next Code For Greenville event link goes to a page not found, but there is an 'upcoming' event for it in the API and on Meetup.com. 

All that said, I think we'll still want to either hide or make cancelled events visually obvious if the event's status == cancelled

**Comment by JSn1nj4** [comment]
So...
1. Merge recent changes into this PR
2. Visually distinguish (or hide) cancelled events

I think I can handle that. I'll look into that beginning over my lunch break today. Thanks for bringing those up.

**Comment by JSn1nj4** [comment]
Ok, so...
1. Visually distinguish cancelled events
2. Look into bad/old event page links?

I'll open another PR to try to handle these.

**Comment by allella** [comment]
I think the bad/old events issue is in the caching and not something to fix on the front-end.

Also, you it may make more sense to just not show cancelled events on the homepage.  We can still show them on the events page and calendar page in case someone is looking to see the status.  What do you think?

**Comment by allella** [comment]
You can create a new branch from develop because that has your recent PR and Zach's too.  The branch used for #64 can be deleted and a new PR and branch used for any additional changes.

**Comment by allella** [comment]
@JSn1nj4 the Code For Greenville events on Oct 6th and Oct 27th are now cancelled.

Assuming the event data isn't cached on the HG side, this should now show in the API data.

I feel we should not show cancelled events on the homepage and flag them as cancelled on the calendar and events page using a color like red, perhaps a font icon, and the word cancelled.

Does that sound like a plan to you and @zach2825 ?

**Comment by zach2825** [comment]
Events are cached in the console commands. I think they're scheduled in cron. I do agree that cancelled events could still show up with a different by color or something

**Comment by allella** [comment]
@zach2825  both stage and live have a crontab setup. I ran it manually and it says "No scheduled commands are ready to run."

I'm not sure if that means the cache is up to date, or it will be run at some future interval.  What's determining how often the API is cached?

I see SESSION_LIFETIME=120 in the .env, but I suspect that's the browser / cookie session lifetime.  As an aside, is 120 minutes?  Seems that could / should be higher on stage and live.

**Comment by zach2825** [comment]
It's supposed to run every hour.

https://github.com/codeforgreenville/hackgreenville-com/blob/develop/app/Console/Kernel.php

**Comment by zach2825** [comment]
This is the command that is ran to import the events.

https://github.com/codeforgreenville/hackgreenville-com/blob/develop/app/Console/Commands/PullEventsCommand.php

**Comment by allella** [comment]
We have this in the crontabs on stage and live

`* * * * * cd ~/public_html/hack && php artisan schedule:run >> /dev/null 2>&1`

**Comment by allella** [comment]
I just ran ` php artisan pull:events` and it updated on stage.

It doesn't look like stage has any indication of cancelled events and I figure @JSn1nj4 could help with that on all of these pages if he has the time and interest.

**Comment by JSn1nj4** [comment]
Hey guys. Sorry, just catching up on discussion...

**Comment by JSn1nj4** [comment]
I just ran into this error when I ran `php artisan pull:events`:
```
   ErrorException 

  Trying to get property 'id' of non-object

  at D:\dev\codeforgreenville\hackgreenville-com\app\Console\Commands\PullEventsCommand.php:76
    73|                 $venue = Venue::firstOrCreate([
    74|                     'address'  => array_get($event, 'venue.address'),
    75|                     'zipcode'  => array_get($event, 'venue.zip'),
  > 76|                     'state_id' => $state->id,
    77|                 ], [
    78|                     'address'  => array_get($event, 'venue.address'),
    79|                     'zipcode'  => array_get($event, 'venue.zip'),
    80|                     'state_id' => $state->id,
```

I also ran `php artisan pull:events --debug` for a sample:

```
array:14 [
  "created_at" => "2020-09-21T17:15:45Z"
  "data_as_of" => "2020-10-08T17:40:10Z"
  "description" => "It's Virtual Networking for the Tech Community."
  "event_name" => "#592 Virtual Tech After Five - Little Rock, AR"
  "group_name" => "Tech After Five"
  "nid" => "31"
  "rsvp_count" => null
  "status" => "upcoming"
  "tags" => ""
  "time" => "2020-10-08T22:30:00Z"
  "url" => "https://www.eventbrite.com/e/592-virtual-tech-after-five-little-rock-ar-tickets-122109991271"
  "uuid" => "30fae35b-6cc4-4b49-b24b-75972231507c"
  "venue" => null
  "localtime" => Carbon\Carbon @1602196200^ {#802
    #constructedObjectId: "000000005e13596f00000000708bf180"
    #localMonthsOverflow: null
    #localYearsOverflow: null
    #localStrictModeEnabled: null
    #localHumanDiffOptions: null
    #localToStringFormat: null
    #localSerializer: null
    #localMacros: null
    #localGenericMacros: null
    #localFormatFunction: null
    #localTranslator: null
    #dumpProperties: array:3 [
      0 => "date"
      1 => "timezone_type"
      2 => "timezone"
    ]
    #dumpLocale: null
    date: 2020-10-08 18:30:00.0 America/New_York (-04:00)
    timezone: "America/New_York"
  }
]

**Comment by JSn1nj4** [comment]
I'm having this happening now when I use `php artisan pull:events`:

```
Trying to get property 'id' of non-object

  at D:\dev\codeforgreenville\hackgreenville-com\app\Console\Commands\PullEventsCommand.php:76
    73|                 $venue = Venue::firstOrCreate([
    74|                     'address'  => array_get($event, 'venue.address'),
    75|                     'zipcode'  => array_get($event, 'venue.zip'),
  > 76|                     'state_id' => $state->id,
    77|                 ], [
    78|                     'address'  => array_get($event, 'venue.address'),
    79|                     'zipcode'  => array_get($event, 'venue.zip'),
    80|                     'state_id' => $state->id,

  1   D:\dev\codeforgreenville\hackgreenville-com\app\Console\Commands\PullEventsCommand.php:76
      Illuminate\Foundation\Bootstrap\HandleExceptions::handleError()

  2   D:\dev\codeforgreenville\hackgreenville-com\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:32
      App\Console\Commands\PullEventsCommand::handle()
```

Not sure what to make of this right this moment. Isn't Eloquent supposed to give you objects to work with instead of arrays (referring to line 70 of that same file)?

**Comment by JSn1nj4** [comment]
Welp... Forgot to run `php artisan db:seed`... Thanks for the reminder @zach2825. 😅
