### ISSUE TITLE
Upgrade laravel from 6.x to 7.x

### ISSUE THREAD

**Issue by zach2825** [codeforgreenville/hackgreenville-com#59]

**Comment by allella** [comment]
Cool. Shall I pull this to the stage domain, or would you like to do it?

**Comment by zach2825** [comment]
Its ok to stage. Just needs some looking over.. I have to step away for a bit thou

**Comment by allella** [comment]
Thanks. This is now staged.  If it looks good, then let me know when to pull it live.

**Comment by allella** [comment]
Actually, I forgot to merge the PR. Let me do that and pull it again.
