### ISSUE TITLE
Upgrade to laravel 8

### ISSUE THREAD

**Issue by zach2825** [codeforgreenville/hackgreenville-com#65]
https://laravel.com/docs/8.x/upgrade

The project is currently on 7.3.0 and laravel 8 is out now with performance updates, security adds, and amazing new features
https://laravel.com/docs/8.x/releases

**Comment by JSn1nj4** [comment]
When upgrading to a new Laravel version, do you normally incorporate _all_ of the changes (including the "miscellaneous" ones) or just the major ones covered directly in the [upgrade guide](https://laravel.com/docs/8.x/upgrade)?

**Comment by zach2825** [comment]
Yes, if it applied lol lke we don't have updated for cashier for example.
