### ISSUE TITLE
Remove target=_blank from links on stateless pages

### ISSUE THREAD

**Issue by jdonboch** [codeforgreenville/hackgreenville-com#88]
As discussed in PR #87 , some of the links behaviors are inconsistent where some use `target=_blank` and some do not.  After researching the best practices and [opinions on the UX Stack Exchange](https://ux.stackexchange.com/questions/5397/whats-your-take-on-target-blank) indicate that the usage of target=_blank is no longer best practice as it takes control away from users with how they want to open links and, anecdotally, usability testing shows that `target=_blank` causes more confusion than benefit.

We should update the links on stateless pages (i.e. all the HackGreenville pages) and mark them as an external link (`rel=external`) so that we can later define styles or the browser can better indicate to the user that the page is external but not force new tabs/windows to be open.

**Comment by allella** [comment]
Sounds good.
