### ISSUE TITLE
Hackgreenville.com Redesign

### ISSUE THREAD

**Issue by allella** [codeforgreenville/hackgreenville-com#9]

**Comment by zach2825** [comment]
I'd like to present the idea of using this laravel instance as the backend and a seperate project as a frontend using something like nuxt with a theme like vuetify

I could update the code and create the base nuxt ui, configure nuxt on apache on a lightsail instance or something. It cost like 10 dollars a month

* [nuxtjs](https://nuxtjs.org/)
* [Vuetify](https://vuetifyjs.com/en/components/calendars)
* [Laravel passport](https://laravel.com/docs/5.8/passport)

**Comment by allella** [comment]
@vaaish @pamelawoodbrowne @jeremywight and Casey Gold have done a survey to suss out the next phase of user desires.  It would be nice to improve the look and UX of the site in the processes.

I'll defer to those folks. However, we do have a free Apache host that I'm well versed in so preference at this point would be to host for free, CFG managed server(s) vs paid setups.

Case in point, I just spend about 8 hours figuring out and moving a Python-based events API from a free Heroku that failed yesterday morning. The original dev moved to Virginia and checked-out on the project.

**Comment by zach2825** [comment]
I have that same internal debate on every project lol. Free is always good. For nuxt, if people like that option, if the server can host nginx or apache as a proxy server so it can handle ssl if need and run something like pm2 for the node server. It's the basic setup I use.

**Comment by zach2825** [comment]
I would like to add nuxt is my favorite but by no means the only thing I'd be open to working with. Next is also great if people like react. Just nuxt is easier, IMO. I'd be happy to help on the project to make it more successful

**Comment by vaaish** [comment]
@zach2825 @allella @jeremywight @pamelawoodbrowne  

It's been a bit since I looked at the survey results since I'm preparing to move in the next few weeks, but I don't recall it gave much more insight for us. I'm not really particular on the backend or framework we use to build the site myself, but it would be good to know any constraints going in so we don't design things that aren't going to work.

**Comment by zach2825** [comment]
Good point no sense in overworking the project.

**Comment by zach2825** [comment]
You can probably closed out this task. So we can start adding specific items to work on. Like set bootstrap 4 variables for the colors or set the brand logo and favicon

**Comment by allella** [comment]
Interested to see if @vaaish has thoughts on design elements once the recent Larvel, cleanup, and design tweaks go live.

Not trying to discount the work @zach2825 has been doing, but it's been more focused on technical cleanup and some visual and UX improvements, but to this point we've not taken a holistic review of the design.

We'll take what we can get, but if Aaron sees is still free to assist then we should tie him in at some point soon, perhaps when the cleanup is live?

**Comment by allella** [comment]
Started a conversation on the HG Slack to get some input, keywords, and such from the broader community to seed the copy
https://app.slack.com/client/T0420TN6E/C0420TN6U/thread/C0420TN6U-1575574236.073000?cdn_fallback=1

**Comment by allella** [comment]
Closing this issue so we can focus on specific tasks / issues related to the new layout and design.
