### ISSUE TITLE
Event Calendar - Events often sending you to a 404 page

### ISSUE THREAD

**Issue by jeremywight** [codeforgreenville/hackgreenville-com#90]
What: Clicking the event URL from the event details often returns a 404 error.

Steps to Reproduce: Go to the Hackgreenville page and select the [calendar](https://hackgreenville.com/calendar) of events. Randomly select some meetings and visit the url and notice that most take you to a 404 page. It appears that this happens when a recurring meeting is changed, the url continues to point to the old event id url which returns a 404.

**Comment by jeremywight** [comment]
Here is the API data which appears to return the correct url: https://events.openupstate.org/api/gtc 

It's possible this is a caching issue. If so I would suggest we remove the caching layer.

**Comment by allella** [comment]
@zach2825 sorry to bother again.  Looks like a new issue here and doesn't seem to be with the events API.

**Comment by zach2825** [comment]
Hey, I can factor out the caching part or make the command run more often than an hour. Right now there is a scheduled job that runs every hour defined here [https://github.com/codeforgreenville/hackgreenville-com/blob/develop/app/Console/Kernel.php#L33](events schedule) which calls this command [https://github.com/codeforgreenville/hackgreenville-com/blob/develop/app/Console/Commands/PullEventsCommand.php](pull:events)

**Comment by allella** [comment]
@zach2825 I ran all of the commands below last night and it didn't seem to make a difference. I'm not sure what's going on here. Maybe it's caching related, we seem to have both missing and incorrect events on the calendar and events list.

For instance, Women Who Code is in the API for March 4th, but it's not on the HG site.  Python shows on the HG site for March 9th, but there's no such event in the API.

![image](https://user-images.githubusercontent.com/1777776/109823116-a3387900-7c05-11eb-8a2e-1b283643cdb5.png)

![image](https://user-images.githubusercontent.com/1777776/109823153-ac294a80-7c05-11eb-9cfc-84b0c389be05.png)
  

```
php artisan cache:clear
php artisan pull:events
php artisan schedule:run
```

**Comment by zach2825** [comment]
The events are cached in the database; you don't need `cache:clear.`

you'd only need `php artisan pull:events` 

The `php artisan schedule:run` command will run scheduled commands [defined here](https://github.com/codeforgreenville/hackgreenville-com/blob/develop/app/Console/Kernel.php#L32-L33).

What that command does:

- call the upstate API to get events. In [this file line 24](https://github.com/codeforgreenville/hackgreenville-com/blob/develop/app/Http/Clients/UpstateClient.php#L24). 
  - In the array map callback, the only thing that happens there is to convert the time that comes back to UTC to store it in the database. 
- Then, in the `pull:events` command, it will loop all the returned events
- Either get or create the event location in the database [line 72](https://github.com/codeforgreenville/hackgreenville-com/blob/develop/app/Console/Commands/PullEventsCommand.php#L72-L87) that will set the event id for the event.
- Update or create the event in the database using [this data](https://github.com/codeforgreenville/hackgreenville-com/blob/develop/app/Console/Commands/PullEventsCommand.php#L54-L64) on [this line](https://github.com/codeforgreenville/hackgreenville-com/blob/develop/app/Console/Commands/PullEventsCommand.php#L92) 
  The status of the event from the API is 'canceled,' then the is_cancelled column is set with the current date and time to set the canceled colors on the calendar to show people the event was canceled. 
- then the frontend will look in the database for current events that match the date range and render those to the calendar.

The event URL comes from [the API](https://github.com/codeforgreenville/hackgreenville-com/blob/develop/app/Console/Commands/PullEventsCommand.php#L62) 

@allella or @jeremywight, does there seem to be anything wrong with that logic?

I created the commands early on to normalize the data to make creating the calendar easier and ensure that if the API were ever slow/ down, it would not break the calendar page.

**Comment by allella** [comment]
Actually, one of the Cocoaheads events on the calendar for today is correct.  It looked like it was tomorrow because of the GTC timing.  Still, the other two events for today, Python and the other Cocoaheads, are not in the [API](https://events.openupstate.org/api/gtc)  and appear as either upcoming or cancelled.

So, the mystery is where are those extra events coming from.

**Comment by allella** [comment]
The [API](https://events.openupstate.org/api/gtc) should return 

`"status": "cancelled"`

as with the Code For Greenville on March 23rd.

I believe canceled Eventbrite events would show the same status.

That was added to the API perhaps 12-18 months ago.

I'm not familiar with the HG logic, so perhaps it's a simple as ignoring `"status": "cancelled"` and only caching exactly what's coming from the [API](https://events.openupstate.org/api/gtc)  ?

**Comment by allella** [comment]
To be clear, between canceled and cancelled, I'm pretty sure we're also making that consistent.  I think Meetup uses "cancelled " and Eventbrite uses "canceled", but the [API](https://events.openupstate.org/api/gtc) should only return "cancelled" for either service.

**Comment by zach2825** [comment]
I explained the logic HG uses in the bullets above. I'm submitting a PR now to change canceled to cancelled when I did the work originally on 9/20/2020 it worked in my testing. I'll get it updated.

I want to point out that even Grammarly thinks cancelled is spelled wrong 
![image](https://user-images.githubusercontent.com/4049321/110501079-d11b3300-80c7-11eb-869b-e57b8a4df770.png)

Typically, America uses canceled.
![image](https://user-images.githubusercontent.com/4049321/110501190-edb76b00-80c7-11eb-94d1-dd59137453b2.png)

**Comment by zach2825** [comment]
That was an inconstancy I had in code too, I used cancelled then someone told me that is not how we spell it in America lol so I started doing canceled.

**Comment by allella** [comment]
Yes, I guess Meetup had a British developer.  It is the most popular source, so we used their preference since it was the majority.

I suppose it's possible organizers are also deleting events, instead of canceling them.  The [API](https://events.openupstate.org/api/gtc)  does not store anything, it fetches fresh each time.  So, if the HG site is storing events where were deleted, then perhaps those are also an issue?

**Comment by zach2825** [comment]
Yeah. I'm working on the updated logic now. Should not take long.

**Comment by allella** [comment]
I merged that PR #92 and the "PyGVL: Lunch Roundtable" events disappeared, but everything else is the same

https://hackgreenville.com/calendar
https://stage.hackgreenville.com/calendar

so perhaps it's the deleted events we're still seeing.

**Comment by zach2825** [comment]
I think I merged to develop

**Comment by allella** [comment]
That right, but I get the same result on develop.

Does your dev calendar look much different than https://stage.hackgreenville.com/calendar ?

The three PyGVL: Lunch Round Table events are the only ones that disappeared when toggling between stage and live.

**Comment by zach2825** [comment]
I tried to rush but what I added should have marked things as cancelled
that were cancelled. I'll spend more quality time with this later today.

**Comment by allella** [comment]
Zach's fix is staged https://stage.hackgreenville.com/calendar

**Comment by allella** [comment]
Alright, @zach2825 fixed an issue on the deployed code and we're now showing the original events as cancelled.  Though, it looks like there are still a few events on the calendar which aren't in the API.  I'll do a review of which ones and create a new to-do. #progress

https://hackgreenville.com/calendar
