### ISSUE TITLE
Inactive Orgs missing on Live Site but Show on Stage

### ISSUE THREAD

**Issue by allella** [codeforgreenville/hackgreenville-com#98]
@zach2825 no rush on getting to this, but I wanted to point out that the issue with the Inactive Organizations was more about the list not showing on live.

The list renders on
https://stage.hackgreenville.com/orgs
but not on
https://www.hackgreenville.com/orgs

I ran `php artisan pull:orgs` but that doesn't seem to do anything.

**Comment by zach2825** [comment]
I just made the list hide when there are no inactive orgs, do you wanna
remove it altogether?

**Comment by allella** [comment]
Actually, I see there's another "Inactive" list above that heading.

Yes, it can be removed entirely.

**Comment by zach2825** [comment]
What do you think about removing the inactive orgs and staggering the other list to use the space better?

![Localhost - Generic Laptop - 2021-15-3 at 3 41 31 PM](https://user-images.githubusercontent.com/4049321/111211613-febf1b00-85a4-11eb-9d63-3c13cc2d0fbd.jpg)
![Localhost - Nexus 5 - 2021-15-3 at 3 41 42 PM](https://user-images.githubusercontent.com/4049321/111211614-febf1b00-85a4-11eb-84bd-3a214e452b1f.jpg)

**Comment by allella** [comment]
Let's move the inactive to a new page /inactive-orgs and have a link from the /orgs to that page.

It's a valuable thing for historical reference. For instance, when people are searching for a topic group or specific meetup in town, it's helpful to show that it's inactive.  Meetup.com usually deletes groups so someone might tell a friend to check out group XYZ and there's little or no reference to the group existing besides our inactive results in a search engine.

Sound good?

**Comment by zach2825** [comment]
I like it. We could do that or we could even add an accordion on the orgs
page at the bottom so people can view them. if they want.

**Comment by allella** [comment]
I don't have a strong opinion either way. As long as we retain the inactive orgs somewhere the search engines and users can get to it.

**Comment by zach2825** [comment]
ok kewl, the accordion ones the easiest way to go for now I'm happy to
change it if its gross

**Comment by allella** [comment]
Closed via #97
