### ISSUE TITLE
Remaining Calendar / Event Inconsistencies

### ISSUE THREAD

**Issue by allella** [codeforgreenville/hackgreenville-com#99]
@zach2825 again, no rush. We appreciate your work

The [HG Calendar](https://hackgreenville.com/calendar) still has inconsistencies versus the [API](https://events.openupstate.org/api/gtc).

This is a quick sample. I suspect there are more examples if events in the coming weeks are inspected.

### Shows in the API, but not on the HG Site
Tech After Five on 3/16 and 3/17

### Shows on the HG Site, but not in the API
UpstatePHP on 3/18

### Event Name Mismatch
The event name in the API for the 3/18 Wordpress group shows
"event_name": "All About WordPress 5.5 Whats New?",
the event name on the HG site shows "WP Talk Luncheon"

I suspect the ongoing issues are related to storing the previously fetched events in the local database and trying to update them, instead of fetching a copy fresh from the API and storing / caching the events each time.

**Comment by allella** [comment]
This may be another issue, but I'll mention it's difficult to figure out what some of the events are from the event names in the calendar view. So, perhaps using the group name in the calendar would work best and when people click on an event in the calendar it would show the event name and other details.

**Comment by zach2825** [comment]
Imma write some testing for this

**Comment by zach2825** [comment]
I found the issue, I'm grouping by event UUID, I thought they were unique. It looks like I don't have a safe way to identify events. In HG I track canceled events by if they drop out of the API. I do that using the UUID since the event name and other details change. 

Could you check to see if there is any uniquely identifying information that the user cannot change that I can safely depend on? I also expect a UUID for the venue. There is an event that has an empty venue but it shows that it's an online event. Is it ok to assume that events without a venue are online? 

Maybe there is a group UUID for repeating events or something like that.

**Comment by zach2825** [comment]
The conditionals for assigning the venue to the event and for updating or creating the event are here. 

to create a new venue 
I check to see if this collection of values exist already and if they don't I create the record

```
                    'address' => array_get($event, 'venue.address'),
                    'zipcode' => array_get($event, 'venue.zip'),
                    'state_id' => $state->id,
                    'name' => array_get($event, 'venue.name') ?? 'Online event',
```

and for the event, I look for the event UUID. If it exists already I update that record and if it does not exist I insert the new record. See attached screenshot

![Selection_20210318101805](https://user-images.githubusercontent.com/4049321/111641232-53e07400-87d3-11eb-8577-580778c361f8.png)

**Comment by allella** [comment]
@zach2825 

The UUID is in fact set to the group ID in the Python app.  Not sure why. It was probably done that way early on and nobody saw a reason to change it.

The Meetup API has an "id" field on events that looks to be unique in this [Code For Greenville events example](https://api.meetup.com/Code-for-Greenville/events?&sign=true&photo-host=public).

I'll have to run a test to see what the raw data looks like coming back from Eventbrite, but I suspect they will have a unique value.

Is it going to break anything on your end if what's returned isn't of a format like _30fae35b-6cc4-4b49-b24b-75972231507c_ ?

**Comment by allella** [comment]
@zach2825 Eventbrite's API also doesn't have an official UUID for events, but the "id" field is unique.

![image](https://user-images.githubusercontent.com/1777776/111683610-15ab7a80-87fc-11eb-8584-4b0202011543.png)

https://www.eventbriteapi.com/v3/organizers/444331701/events/?token=**YOURTOKENHERE**

So, we could either pass along the unique event.id values from the service.  Or, I suspect we could seed and generate a unique value, but since the [Python events API app](https://github.com/codeforgreenville/upstate_tech_cal_service) doesn't have a database, we can't generate a true UUID on our end and have it be easily reproduced.

**Comment by zach2825** [comment]
I'm ok with id. I can make a code change and rename the db column from
event_uuid to event_id

**Comment by allella** [comment]
Perhaps we should prefix them with something unique so we don't have two event services with the same ID causing a problem?

meetup-14215742
eventbrite-1413346357

**Comment by zach2825** [comment]
the site don't really care as long as its unique

personally I like it thou, so you know where the ID came from.

**Comment by allella** [comment]
Or, we could add something like a "service" value and you could hash your own value off it?

'service': 'meetup',
'id': '14215742',

'service': 'eventbrite',
'id': '1413346357'

**Comment by zach2825** [comment]
I like the api being the source of truth on that. that way if other
applications consume that data then it will be consistent.

**Comment by allella** [comment]
@zach2825 

The [events API](https://events.openupstate.org/api/gtc) has two new fields

```
    "service": "meetup", 
    "service_id": "cqthwryccfbdc", 

```
and the existing _UUID_ value is  now a consistent, unique hash we generate in the Python code using those two "service" values.

Please see if this helps with the issues.

**Comment by allella** [comment]
Since the uuid field is still there, you probably don't even need to change your code. Just reimport things from scratch and hopefully that does the job.  The "service" fields were added to allow for more easily identifying the event service and its original id / key value for other potential use cases.

**Comment by zach2825** [comment]
Yeah we'll have to wipe the database out and re pull events

**Comment by allella** [comment]
Alright. Should I run the following on stage to test? 

```
php artisan db:wipe
php artisan pull:events

```

**Comment by zach2825** [comment]
Pull events and pull:orgs

**Comment by allella** [comment]
Alright, you said "wipe" so I thought it was necessary to wipe what was there.

This looks like progress, but events earlier in the month that actually happened, like Code For Greenville, are showing as cancelled.

https://stage.hackgreenville.com/calendar

**Comment by zach2825** [comment]
I think we should reset the database since the uuid is different. All the
old events would show canceled since they won't match any more.

If you want to reset it to scratch this would reset the database and pull
all the new orgs and new events from the api

php artisan migrate:fresh --seed
php artisan pull:orgs
php artisan pull:events

This is what my local calendar looks like after running those commands
[image: image.png]

**Comment by allella** [comment]
Alright, we're looking pretty good now. I haven't checked a ton of events, but the ones I checked are real.

I had to temporarily pull the last 80 days of events into the API and then trick out the pull:events to use a Jan 1 start date so we had some prior events showing.

There's a manual change on the live server. Can that be removed and/or does it need to be committed to develop and merged into the live code?

```
--- a/app/Console/Commands/PullEventsCommand.php
+++ b/app/Console/Commands/PullEventsCommand.php
@@ -38,7 +38,7 @@ class PullEventsCommand extends Command
         $events = collect(UpstateClient::getEvents());
 
         // get all upcoming events and set keys to uuid so I can set status
-        $dbEvents     = Event::startOfmonth()->whereNull('cancelled_at')->get();
+        $dbEvents     = Event::startOfmonth()->whereNull('cancelled_at')->whereNotNull('event_uuid')->get();
         $dbEventUUIDs = array_map(

```

**Comment by zach2825** [comment]
Awesome! That's great to hear.

That code can be removed, thank you.

**Comment by allella** [comment]
Thanks for figuring it out.  Hopefully we're over the hump again.

**Comment by allella** [comment]
@zach2825 Despite the progress, it looks like we're seeing some new issues on the calendar.

Code For Greenville on the 23rd is a cancelled event and that's how it's marked in the [events API](https://events.openupstate.org/api/gtc).

I also notice the events earlier in the month are all red/cancelled on the calendar, but I know the March 2nd Code For Greenville wasn't cancelled. Perhaps these are just an artifact of importing older events.

I haven't checked the UUIDs to make sure they aren't changing, but I don't see how that would impact showing a cancelled event like the CFG on the 23rd.

Thanks again and sorry this has become a moving target.

**Comment by zach2825** [comment]
yeah, on stage we had to wipe the database and re-import everything. Since
the UUIDS are all invalid HG does not know how to map them.

reset the database with `php artisan migrate:fresh --seed` and run the
other commands to import `php artisan pull:events; php artisan pull:orgs;`

migrate:fresh will drop all tables and re-run migrations to re-create them.
Its safe because everything in there is collected from the API. After the
commands are done HG won't have old events.

**Comment by allella** [comment]
Alright, I purposely imported events from back to Jan 1 2021 so things didn't look empty. I changed the dates temporarily when I ran the imports and then changed it back. Should I not do that again?

I just ran the commands you suggested and it naturally wiped the older events off the calendar, but the issue with the March 23rd Code For Greenville still showing, when it's cancelled, is likely another issue.

**Comment by zach2825** [comment]
I'm sorry I misunderstood, I'll submit a PR now.

**Comment by zach2825** [comment]
I've added a switch to the `pull:events` command that will populate the service and service_id values from the event cache and find dups. using service and service_id. If it finds dups then delete the newest record.

I also changed from using UUID to look at service and service_id and a combination of the 2.

**Comment by allella** [comment]
Alright, I'm going to test this on stage. 

Do I need to run the --fix on just the first pull, or all the time?

I'm going to temporarily set things to pull older events too. Once I do that would I run?

```
php artisan migrate:fresh --seed
php artisan --fix pull:events; php artisan pull:orgs;

```

**Comment by allella** [comment]
Alright, I ran the steps above.

It's already looking much better, but I'll click around a bit.

So, the question is do we need to run --fix all the time?  If so, will the schedule:run  take care of it?

**Comment by allella** [comment]
https://stage.hackgreenville.com/calendar

**Comment by zach2825** [comment]
--fix should only be needed the one time.

**Comment by allella** [comment]
Alright, so I changed the events API to pull the last 90 days. Then, on stage, I ran the import with a temporary past events back to Jan 1 with a temporary ?start_date=2021-01-01 added to app/Http/Clients/UpstateClient.php
I ran everything fresh with

```
php artisan migrate:fresh --seed
php artisan -pull:events; php artisan pull:orgs;

```
Then, I removed the temporary ?start_date=2021-01-01 added to app/Http/Clients/UpstateClient.php and ran the import again 
`php artisan --fix pull:events; php artisan pull:orgs;
`
and it marks many, but not all, of the past events as cancelled.

I also tried running --fix on the 90 day import and then removing it on the second import and it seemed to do the same thing with [the cancelled past events.](https://stage.hackgreenville.com/calendar)

The March 2nd Code For Greenville was an active event, so that one is showing cancelled again.

If the old events are going to be a problem I'll just run the import going forward with no old events.

**Comment by allella** [comment]
I get the same result with various cancelled past events as well when importing everything fresh back to 90 days without the --fix flag, and then run a pull:events for only upcoming events, without using the --fix.

**Comment by allella** [comment]
![image](https://user-images.githubusercontent.com/1777776/112172359-07c67280-8bcb-11eb-9f48-a41ae42f1013.png)

Alright, part of the issue could be the events that are getting cancelled have a "status": "past" or "status" : null  (Eventbrite)

**Comment by allella** [comment]
```
Marking 16 events cancelled in the database. These uuid {"service":"eventbrite","service_id":"142729334281"}, {"service":"meetup","service_id":"ppxpsryccfbdb"}, {"service":"meetup","service_id":"rfhtmryccfbfb"},
 {"service":"meetup","service_id":"spwhfqyccfbgb"}, {"service":"meetup","service_id":"xlxfxryccfbgb"}, {"service":"meetup","service_id":"cqthwryccfblb"}, {"service":"eventbrite","service_id":"144057133765"}, {"s
ervice":"eventbrite","service_id":"142364585307"}, {"service":"meetup","service_id":"276699053"}, {"service":"eventbrite","service_id":"142364719709"}, {"service":"meetup","service_id":"fdfbsryccfbrb"}, {"servic
e":"meetup","service_id":"276400784"}, {"service":"eventbrite","service_id":"145308179677"}, {"service":"meetup","service_id":"wxlwlryccfbwb"}, {"service":"eventbrite","service_id":"142364940369"}, {"service":"m
eetup","service_id":"pclgxryccfbxb"}

```

**Comment by allella** [comment]
Alright, the "status" : null for Eventbrite was them using a "status" : "completed" which we never mapped and normalized to "past".

"service_id" : "142364940369" now returns "status" : "past".  Though, that didn't change anything. The event still gets marked as cancelled on the second run when I remove the temporary 90 day start date.

If I run the ?start_date=2021-01-01 import multiple times it doesn't cancel anything. It's only when I import old events and then switch the import to only pull upcoming events that some, but not all, of the past events get marked as cancelled.

**Comment by allella** [comment]
@zach2825 interestingly, the past events which are showing as cancelled all seem to be in the 1 month prior to today.  Older events from the first half of Feb and Jan are only showing cancelled if they were actually cancelled.

**Comment by zach2825** [comment]
The conditions that mark the event canceled are based on service and
service_id

   - if the database has results that don't come back from the API they get
   canceled.
   - if the API says it canceled they get marked cancelled

old events before my latest work don't have the service and service_id
columns so I added the --fix option. --fix will get all events missing
"service" and populate service and service_id from the events cache column
then the pull:events command will go on with its normal work flow.

**Comment by allella** [comment]
I think the condition for "if the database has results that don't come back from the API they get canceled."  will continue to cause an issue.

Events will come and go and just because the API only returns the upcoming events doesn't mean the events that have passed never happened.

I think it's safe to use the status from the events API and update the status on every pull.  If the event was on March 2nd and its last status wasn't "cancelled", then I think it should continue to show on the calendar, even though it's already happened.

It is the case that the API may change an event that already happened to "past", but it's also likely the case that as soon as the event is over it will roll off the events API default call, which is only for upcoming events.

Would removing that first condition do the job?

Thanks,
JIm

**Comment by allella** [comment]
The events API goes through the effort of normalizing the statuses for Meetup and Eventbrite and it will convert _from:to_

        'canceled': 'cancelled',
        'live': 'upcoming',
        'ended': 'past',
        'completed': 'past'

So, unless I'm missing an edge case, the events API will return

Statuses that should show on the calendar as active: _upcoming_ and  _past_
Statuses that should show as cancelled: _cancelled_

**Comment by zach2825** [comment]
I think if we could get on a zoom call we could knock out this pretty
quickly. Do you have time in about an hour or tomorrow morning before
9.30am?

**Comment by allella** [comment]
Sorry, just getting back.  How about tomorrow night?

**Comment by zach2825** [comment]
Cool works for me! 6.30pm or 8:00pm

**Comment by allella** [comment]
8PM today is good.  I assume you'll PM me a video link?

**Comment by zach2825** [comment]
8:00 is good I will share a link

**Comment by allella** [comment]
Thanks for the Zoom, @zach2825 

Looking good.

I'll create an issue for using the group_name or group_name + event_name on the calendar, but no rush.  You've done enough lately.
